src/correllbio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^imagej/', include("imagej.urls", namespace='imagej')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/imagej/urls.py
from django.conf.urls import url
from .views import index, show, create

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<id>\d+)/$', show, name='show'),
    url(r'^create/$', create, name='create'),
]

src/imagej/models.py
from django.db import models
import os
from django.conf import settings


def upload_location(instance, filename):
  return "%s/%s/%s" %('imagej', instance.id, filename)


# Create your models here.
class ImageJ(models.Model):
  title = models.CharField(max_length=120)
  image = models.ImageField(upload_to=upload_location,
                            height_field="height_field",
                            width_field="width_field",
                            null=False)
  height_field = models.IntegerField(default=0)
  width_field = models.IntegerField(default=0)

src/imagej/forms.py
from django import forms

from .models import ImageJ

class ImageJForm(forms.ModelForm):
  class Meta:
    model = ImageJ
    fields = [
      'title',
      'image',
    ]

src/imagej/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import ImageJ
from .forms import ImageJForm
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image

# Create your views here.
def index(request):
  images = ImageJ.objects.all()
  context = {
    'title': 'Index',
    'images': images
  }
  return render(request, 'imagej/index.html', context)

def show(request, id=None):
  instance = get_object_or_404(ImageJ, id=id)
  img = Image.open(instance.image.path).convert('L')

  WIDTH, HEIGHT = img.size

  data = np.asarray(img.getdata())
  data = data.reshape((HEIGHT, WIDTH))
  reduced_data = data.mean(axis=0)
  chart_data = [[i, int(x)] for i, x in enumerate(reduced_data)]

  context = {
    'title': 'Detail',
    'instance': instance,
    'data': chart_data
  }
  return render(request, 'imagej/show.html', context)

def create(request):
  form = ImageJForm(request.POST, request.FILES or None)
  if form.is_valid():
    instance = form.save(commit=False)
    instance.save()
  context = {
    'title': 'Create',
    'form': form
  }
  return render(request, 'imagej/form.html', context)

src/templates/imagej/form.html
{% extends "layouts/base.html" %}

{% block title %} {{ block.super }} | Create {% endblock title %}

{% block content %}
    <h1>This is a Form</h1>

    <form method="POST" action="/imagej/create/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Analyse">
    </form>

{% endblock content %}

src/templates/imagej/index.html
{% extends "layouts/base.html" %}

{% block title %} {{ block.super }} | Index {% endblock title %}

{% block content %}
  <div class="row">

    {% for image in images %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="card-img-top" src="{{ image.image.url }}"
               alt="Card image cap">
          <div class="card-body">
            <p class="card-text"><a href="{% url 'imagej:show' id=image.id %}">{{ image.title }}</a></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}

src/templates/imagej/show.html
{% extends "layouts/base.html" %}

{% block title %} {{ block.super }} | Detail {% endblock title %}

{% block content %}
  <h1>Detail of image:</h1>

  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <img class="card-img-top" src="{{ instance.image.url }}"
             alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><a href="{% url 'imagej:show' id=instance.id %}">{{ instance.title }}</a></p>
        </div>
      </div>
      <a href="{% url 'imagej:index' %}">Back</a>
    </div>

    <div class="col-md-8">
      <div class="card mb-4 shadow-sm">
        <div id="highchart"></div>
      </div>
    </div>
  </div>


  <script>
    $(document).ready(function () {
      Highcharts.chart('highchart', {
        chart: {
          type: 'area',
          zoomType: 'x',
          panning: true,
          panKey: 'shift',
          scrollablePlotArea: {
            minWidth: 600
          }
        },

        title: {
          text: 'Image Plot Profile'
        },

        xAxis: {
          labels: {
            format: '{value}'
          },
          title: {
            text: 'Distance (Pixels)'
          }
        },

        yAxis: {
          startOnTick: true,
          endOnTick: false,
          maxPadding: 0.35,
          title: {
            text: 'Gray Value'
          },
          labels: {
            format: '{value}'
          }
        },

        tooltip: {
          headerFormat: 'Distance: {point.x:.1f}<br>',
          pointFormat: '{point.y}',
          shared: true
        },

        legend: {
          enabled: false
        },

        series: [{
          data: {{ data }},
          lineColor: Highcharts.getOptions().colors[1],
          color: Highcharts.getOptions().colors[2],
          fillOpacity: 0.5,
          name: 'Elevation',
          marker: {
            enabled: false
          },
          threshold: null
        }]
      });
    })
  </script>

{% endblock content %}

src/templates/layouts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>{% block title %} Correllbio {% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/highcharts.src.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  {# Custom css files #}
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>

{% include "layouts/header.html" %}
<main role="main">
  {% include "layouts/section_header.html" %}
  <div class="album py-5 bg-light">
    <div class="container">
      {% block content %}

      {% endblock content %}
    </div>
  </div>

</main>
</body>
</html>

src/templates/layouts/header.html
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other
            background context. Make it a few sentences long so folks can pick up some informative tidbits.
            Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
          <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
          <circle cx="12" cy="13" r="4"></circle>
        </svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
              aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

src/templates/layouts/section_header.html
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc.
      Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary my-2">Main call to action</a>
      <a href="#" class="btn btn-secondary my-2">Secondary action</a>
    </p>
  </div>
</section>